# site settings
title: Daphne Kontaxi
subtitle: Portfolio
email: daphne_kon@yahoo.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: dkonn.github.io
author: Daphne Kontaxi
street_address: ""
city: Athens
state: 
zip_code: 118 23
country: Greece
phone: (+30) 6986673539

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/daf2kon/
linkedin_url: https://www.linkedin.com/in/daphne-kontaxi-7a391519b/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
